comment: false
coverage:
  notify:
    slack:
      default:
        url: "https://hooks.slack.com/services/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"
        threshold: 1%
        only_pulls: false
        branches: null
        flags: null
        paths: null
  
    

